version: '3.7'
services:
  ying-front:
    env_file:
      - .env
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    ports:
      - target: ${EXPOSE_PORT}
        published: ${SERVER_PORT}
        protocol: tcp
        mode: host